name: Build Intellij Idea Fcitx
 
on: 
  push:
    branches: 
    - master
jobs:
  compile-fcitx: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: compile OpenFX
        run: |
            mkdir test
            cd test
            pwd
      - name: compile JetBrainsRuntime
        run: |
            cd ..
            pwd
            mkdir demo
            ls
