name: Build Intellij Idea Fcitx
 
on: push
jobs:
  compile-fcitx: 
    runs-on: ubuntu-latest
    steps:
      - name: compile OpenFX
        run: |
            mkdir test
            cd test
            pwd
      - name: compile JetBrainsRuntime
        run: |
            cd ..
            pwd
            mkdir demo
            ls
