name: Deploy Intellij Idea Fcitx
 
on:
  push:
    branches:
      - master
jobs:
  compile-fcitx:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: ./.github/scripts/build.sh
        shell: bash

