name: Build Intellij Idea Fcitx
 
on: push
jobs:
  compile-fcitx: 
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: |
            cd .github/scripts
            ./build.sh


